### PR TITLE
python: add a few basic programs

### PR DESCRIPTION
**Pull request by rupansh**
armstrong, dectobin, facctorial, fibonacci and palindrome

### CODE REVIEW

**Comment by msfjarvis** [comment]
Rebase on master for style checking to kick in.

**Comment by rupansh** [comment]
@msfjarvis i dont think black supports glob kek

**Comment by msfjarvis** [comment]
> @msfjarvis i dont think black supports glob kek

:man_shrugging: 

```shell
(venv) msfjarvis@ryzenbox: python (master) $ black --check *.py
All done! ✨ 🍰 ✨
4 files would be left unchanged.
(venv) msfjarvis@ryzenbox: python (master) $ black --version
black, version 19.3b0
```

**Comment by rupansh** [comment]
> > @msfjarvis i dont think black supports glob kek
> 
> 🤷‍♂
> 
> ```shell
> (venv) msfjarvis@ryzenbox: python (master) $ black --check *.py
> All done! ✨ 🍰 ✨
> 4 files would be left unchanged.
> (venv) msfjarvis@ryzenbox: python (master) $ black --version
> black, version 19.3b0
> ```

should be fine now

**Pull request merged**
