### PR TITLE
Added Stack and Bubble Sort in Kotlin

### PR DESCRIPTION
**Pull request by RKRohk**

### CODE REVIEW

**Comment by msfjarvis** [comment]
This needs to be rebased on master and converted into some sort of standalone project that can be tested through CI.

**Comment by RKRohk** [comment]
Okay, will do

**Comment by msfjarvis** [comment]
Closing for inactivity

**Comment by msfjarvis** [comment]
I've added a Kotlin skeleton to the repo with a testing setup included alongwith stylechecks, please rebase on that if you ever pick this up.

**Pull request closed without merging**
